version: '3.9'
services:
  fastapi_server:
    container_name: planetracker_fastapi_server
    build: ./backend
    restart: always
    command: "sh -c 'gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120'"
    volumes:
      - ./backend/app:/code
    expose:
      - 8000
    env_file: ".env"

  caddy_reverse_proxy:
    container_name: planetracker_caddy_reverse_proxy
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - EXT_ENDPOINT1=${EXT_ENDPOINT1}
      - LOCAL_1=${LOCAL_1}
      - LOCAL_2=${LOCAL_2}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  postgres:
    image: postgis/postgis:16-3.4
    container_name: plane-tracker-db
    environment:
      POSTGRES_DB: planetracker
      POSTGRES_USER: planetracker
      POSTGRES_PASSWORD: planetracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: plane-tracker-redis
    ports:
      - "6379:6379"

volumes:
  caddy_data:
  caddy_config: 
  postgres_data: